backend:
  name: github
  repo: ryuiro-kitsune/celadon.moe
  branch: main # Branch to update (optional; defaults to master)
  site_domain: https://celadon.moe
  use_graphql: true
  base_url: https://celadon.moe
  auth_endpoint: /api/auth
media_folder: "source/images/"
public_folder: "/images"
publish_mode: editorial_workflow
collections:
  - name: "blog"
    label: "Blog"
    folder: "source/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
